version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports: 
        - "5432:5432"
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=express_typescript_pg_database
        - POSTGRES_HOST=localhost
    volumes: 
        - ./postgres-data:/var/lib/postgresql/data